name: Package Bug Report
description: Something went wrong with the installation of a package? Or did you find an unexpected behavior?
title: ""
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! Please fill out out the necessary information as complete as you can. Remember, it is better to include too much information, than too little.
  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: |
        Which version of the package did you find this bug for?
      placeholder: ex 5.0.0 or 4.0.0 -> 4.1.0 for upgrades.
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current Behaviour
      description: Please provide a concise description of what you are experiencing.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: Please provide a concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: |
        How can we reproduce the behaviour that you are seeing, please include the exact steps that is needed.
        If no steps are included, and we are unable to reproduce the issue it may be closed without notice.
      placeholder: |
        1. In this environment...
        2. Run '...'
        3. See error...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        What environment did you encounter the bug in? Operating System, .NET Version, PowerShell Version and the shell/terminal emulator used (ie. PowerShell, CMD).

        NOTE: _PowerShell Core is not supported_.

        TIP:
        - To get the Operating System, run `[System.Environment]::OSVersion.ToString()` in a PowerShell session.
        - To get the PowerShell Version, run `$PSVersionTable` in a PowerShell session.
      value: |
        - Operating System:
        - PowerShell Version:
        - Shell:
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Chocolatey Log
      description: |
        Include the log that has been created by Chocolatey. If possible, it is prefered that this be a link to a file located at https://gist.github.com instead of embedded directly inside the issue. Remember to remove any **sensitive information** from the log before posting.

        Tip: For standard installations, the Chocolatey log file is located at `C:\ProgramData\chocolatey\logs\chocolatey.log`.
      render: shell
    validations:
      required: true
  - type: textarea
    id: additional-details
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering?

        Tip: You can attach images by clicking this area to highlight it and then drag files in.
    validations:
      required: false
