name: publish
on:
  workflow_dispatch:
  schedule:
  - cron: "0 16 2 * *"

jobs:
  publish:
    runs-on: windows-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Prepare workspace
        run: |
          tree
          cd ci-helpers
          ./run_publish.ps1
          cd ../
          tree
          dir texlive\tools

      - name: Check for modified files
        shell: bash
        id: git-check
        run: |
          git status
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
          echo ::set-output name=version::$(python ci-helpers/showversion.py)

      - name: Commit and Push
        shell: bash
        if: steps.git-check.outputs.modified == 'true'
        env:
          email_address: ${{ secrets.EMAIL_ADDRESS }}
          VERSION: ${{ steps.git-check.outputs.version }}
        run: |
          git config user.name "Naveen M K"
          git config user.email "${email_address}"
          git add .
          git commit -m "Texlive Release ${VERSION}"
          git push
      - name: Push to Chocolatey
        env:
          CHOCO_KEY: ${{ secrets.CHOCO_API_KEY }}
        id: choco-push
        run: |
         cd texlive
         choco pack
         $nupkgFile=$(Resolve-Path *.nupkg)
         echo "::set-output name=nupkg::$($nupkgFile)"
         choco apikey --key $Env:CHOCO_KEY --source https://push.chocolatey.org/
         choco push --source https://push.chocolatey.org/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.choco-push.outputs.nupkg }}
          artifactContentType: application/zip
          name: Release Tex Live Chocolatey ${{ steps.git-check.outputs.version }}
          tag: v${{ steps.git-check.outputs.version }}
          body: |
            This is the Scheduled Release of Tex Live Chocolatey Package.
            Here, the `.nupkg` of the installer is uploaded as release asset.
