name: Debug with Tmate
on:
  workflow_dispatch:

jobs:
  debug-shell:
    name: Debug with Tmate
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: Debug with tmate
        uses: mxschmitt/action-tmate@v3
